<a href="https://colab.research.google.com/github/hnkm525/Infinity_Numpy/blob/main/InfinityNumpy_chap2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# 2章演習問題解答

In [1]:
import numpy as np  

In [ ]:
# Q1:全て0と1
print(np.ones(3))
print(np.zeros(7))

[1. 1. 1.]
[0. 0. 0. 0. 0. 0. 0.]


In [ ]:
# Q2:整数のNumPy配列
o3 = np.ones(3, dtype=np.int32)
z7 = np.zeros(7, dtype=np.int32)
print(o3, o3.dtype)
print(z7, z7.dtype)

[1 1 1] int32
[0 0 0 0 0 0 0] int32


In [ ]:
# Q3:中間地点に代入
xs = np.zeros(5, dtype=np.int32)
xs[2] = 1
print(xs)

[0 0 1 0 0]


In [ ]:
# Q4:奇数と偶数のインデックス(1)
xs = np.zeros(10, dtype=np.int32)
xs[::2] = 1
print(xs)

[1 0 1 0 1 0 1 0 1 0]


In [ ]:
# Q5:奇数と偶数のインデックス(2)
xs = np.ones(10, dtype=np.int32)
xs[::2] = 0
print(xs)

[0 1 0 1 0 1 0 1 0 1]


In [ ]:
# Q6:FizzBuzz
fzbz = np.arange(1, 101, dtype=np.int32)
fzbz = fzbz.astype(np.object)
fzbz[2::3] = "Fizz"
fzbz[4::5] = "Buzz"
fzbz[14::15] = "FizzBuzz"
print(fzbz)

[1 2 'Fizz' 4 'Buzz' 'Fizz' 7 8 'Fizz' 'Buzz' 11 'Fizz' 13 14 'FizzBuzz'
 16 17 'Fizz' 19 'Buzz' 'Fizz' 22 23 'Fizz' 'Buzz' 26 'Fizz' 28 29
 'FizzBuzz' 31 32 'Fizz' 34 'Buzz' 'Fizz' 37 38 'Fizz' 'Buzz' 41 'Fizz' 43
 44 'FizzBuzz' 46 47 'Fizz' 49 'Buzz' 'Fizz' 52 53 'Fizz' 'Buzz' 56 'Fizz'
 58 59 'FizzBuzz' 61 62 'Fizz' 64 'Buzz' 'Fizz' 67 68 'Fizz' 'Buzz' 71
 'Fizz' 73 74 'FizzBuzz' 76 77 'Fizz' 79 'Buzz' 'Fizz' 82 83 'Fizz' 'Buzz'
 86 'Fizz' 88 89 'FizzBuzz' 91 92 'Fizz' 94 'Buzz' 'Fizz' 97 98 'Fizz'
 'Buzz']


In [ ]:
# Q7:FizzBuzzしばりプレイ
# Q6が既にMOD縛りをしてるので省略

In [ ]:
# Q8:世界のナベアツ
ind = np.arange(1, 101, dtype=np.int32)
nbat = ind.astype(np.object)
nbat[ind%10 == 3] = "アホ"
nbat[ind//10 == 3] = "アホ"
nbat[ind%3 == 0] = "アホ"
print(nbat)

[1 2 'アホ' 4 5 'アホ' 7 8 'アホ' 10 11 'アホ' 'アホ' 14 'アホ' 16 17 'アホ' 19 20 'アホ'
 22 'アホ' 'アホ' 25 26 'アホ' 28 29 'アホ' 'アホ' 'アホ' 'アホ' 'アホ' 'アホ' 'アホ' 'アホ'
 'アホ' 'アホ' 40 41 'アホ' 'アホ' 44 'アホ' 46 47 'アホ' 49 50 'アホ' 52 'アホ' 'アホ' 55
 56 'アホ' 58 59 'アホ' 61 62 'アホ' 64 65 'アホ' 67 68 'アホ' 70 71 'アホ' 'アホ' 74
 'アホ' 76 77 'アホ' 79 80 'アホ' 82 'アホ' 'アホ' 85 86 'アホ' 88 89 'アホ' 91 92 'アホ'
 94 95 'アホ' 97 98 'アホ' 100]


In [ ]:
# Q9:平方数
xs = np.arange(200, dtype=np.int32)
xs[np.logical_not(np.isclose(np.sqrt(xs)%1, 0))] = 0
print(xs)

[  0   1   0   0   4   0   0   0   0   9   0   0   0   0   0   0  16   0
   0   0   0   0   0   0   0  25   0   0   0   0   0   0   0   0   0   0
  36   0   0   0   0   0   0   0   0   0   0   0   0  49   0   0   0   0
   0   0   0   0   0   0   0   0   0   0  64   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0  81   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0 100   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0 121   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
 144   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0 169   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0 196   0
   0   0]


In [ ]:
# Q10:等速直線運動
print(np.linspace(15, 65, 61))

[15.         15.83333333 16.66666667 17.5        18.33333333 19.16666667
 20.         20.83333333 21.66666667 22.5        23.33333333 24.16666667
 25.         25.83333333 26.66666667 27.5        28.33333333 29.16666667
 30.         30.83333333 31.66666667 32.5        33.33333333 34.16666667
 35.         35.83333333 36.66666667 37.5        38.33333333 39.16666667
 40.         40.83333333 41.66666667 42.5        43.33333333 44.16666667
 45.         45.83333333 46.66666667 47.5        48.33333333 49.16666667
 50.         50.83333333 51.66666667 52.5        53.33333333 54.16666667
 55.         55.83333333 56.66666667 57.5        58.33333333 59.16666667
 60.         60.83333333 61.66666667 62.5        63.33333333 64.16666667
 65.        ]


In [ ]:
# Q11:連番べき乗
xs = np.arange(10) ** np.arange(10)
print(xs)

[        1         1         4        27       256      3125     46656
    823543  16777216 387420489]


In [ ]:
# Q12:三角関数の加法定理
# sin(x + y) = sin(x)cos(y) + cos(x)sin(y)
alpha = np.linspace(0, 2*np.pi, 50)
beta = np.arange(50)
sahen = np.sin(alpha + beta)
uhen = np.sin(alpha)*np.cos(beta) + np.cos(alpha)*np.sin(beta)
print(np.isclose(sahen, uhen))

[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True]


In [13]:
# Q13:GoToトラベル
tour_costs = np.arange(1000, 30000+1, 500, dtype=np.int32)
discounted_tour_costs = tour_costs * 0.65
applied_coupon = np.round(tour_costs * 0.15 + 1, -3)
payment = (tour_costs - discounted_tour_costs).astype(np.int32)
actual_payment = (payment - applied_coupon).astype(np.int32)

for x, y, z in zip(tour_costs, payment, actual_payment):
  print(x, y, z)

1000 350 350
1500 525 525
2000 700 700
2500 875 875
3000 1050 1050
3500 1225 225
4000 1400 400
4500 1575 575
5000 1750 750
5500 1925 925
6000 2100 1100
6500 2275 1275
7000 2450 1450
7500 2625 1625
8000 2800 1800
8500 2975 1975
9000 3150 2150
9500 3325 2325
10000 3500 1500
10500 3675 1675
11000 3850 1850
11500 4025 2025
12000 4200 2200
12500 4375 2375
13000 4550 2550
13500 4725 2725
14000 4900 2900
14500 5075 3075
15000 5250 3250
15500 5425 3425
16000 5600 3600
16500 5775 3775
17000 5950 2950
17500 6125 3125
18000 6300 3300
18500 6475 3475
19000 6650 3650
19500 6825 3825
20000 7000 4000
20500 7175 4175
21000 7350 4350
21500 7525 4525
22000 7700 4700
22500 7875 4875
23000 8050 5050
23500 8225 4225
24000 8400 4400
24500 8575 4575
25000 8750 4750
25500 8925 4925
26000 9100 5100
26500 9275 5275
27000 9450 5450
27500 9625 5625
28000 9800 5800
28500 9975 5975
29000 10150 6150
29500 10325 6325
30000 10500 5500


In [15]:
# Q14:小数の丸め方
x = np.linspace(-1, 1, 9)
fl = np.floor(x)
ce = np.ceil(x)
ro = np.round(x)
Integer = x.astype(np.int32)
for a, b, c, d, e in zip(x, fl, ce, ro, Integer):
  print(a, b, c, d, e)
  print(a.dtype, b.dtype, c.dtype, d.dtype, e.dtype)
 

-1.0 -1.0 -1.0 -1.0 -1
float64 float64 float64 float64 int32
-0.75 -1.0 -0.0 -1.0 0
float64 float64 float64 float64 int32
-0.5 -1.0 -0.0 -0.0 0
float64 float64 float64 float64 int32
-0.25 -1.0 -0.0 -0.0 0
float64 float64 float64 float64 int32
0.0 0.0 0.0 0.0 0
float64 float64 float64 float64 int32
0.25 0.0 1.0 0.0 0
float64 float64 float64 float64 int32
0.5 0.0 1.0 0.0 0
float64 float64 float64 float64 int32
0.75 0.0 1.0 1.0 0
float64 float64 float64 float64 int32
1.0 1.0 1.0 1.0 1
float64 float64 float64 float64 int32


In [23]:
# Q15:ランダムな個数の配列
for i in range(5):
  randarr = np.random.randn(10)
  print(np.ones_like(randarr[randarr>=0]), np.zeros_like(randarr[randarr<0]))

[1. 1. 1. 1. 1. 1.] [0. 0. 0. 0.]
[1. 1. 1. 1. 1.] [0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1.] [0. 0. 0.]
[1. 1. 1. 1.] [0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.] [0. 0. 0. 0. 0.]


In [33]:
# Q16:要素が10連続の配列
ans = np.empty(0)
for i in range(5):
  ans = np.concatenate([ans, np.full(10, i, dtype=np.int32)])
print(ans)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 2. 2. 2.
 2. 2. 2. 2. 2. 2. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 4. 4. 4. 4. 4. 4. 4. 4.
 4. 4.]


In [40]:
# Q17:おーばーふろーあんだーふろー
arr = np.array([0, 1, 2, 253, 254, 255], dtype=np.uint8)
print(arr+1)
print(arr-1)
print(arr*2)
print(arr/2)
print(arr//2)



[  1   2   3 254 255   0]
[255   0   1 252 253 254]
[  0   2   4 250 252 254]
[  0.    0.5   1.  126.5 127.  127.5]
[  0   0   1 126 127 127]


In [44]:
# Q18:頭打ち処理
arr = arr = np.array([0, 1, 2, 253, 254, 255], dtype=np.int32)
print(np.clip(arr+1, 0, 255).astype(np.uint8))
print(np.clip(arr-1, 0, 255).astype(np.uint8))
print(np.clip(arr*2, 0, 255).astype(np.uint8))
print(np.clip(arr/2, 0, 255).astype(np.uint8))
print(np.clip(arr//2, 0, 255).astype(np.uint8))


[  1   2   3 254 255 255]
[  0   0   1 252 253 254]
[  0   2   4 255 255 255]
[  0   0   1 126 127 127]
[  0   0   1 126 127 127]


In [ ]:
# Q19:魔王と勇者のデータサイエンス
