<a href="https://colab.research.google.com/github/hnkm525/Infinity_Numpy/blob/main/InfinityNumpy_chap2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# 2章演習問題解答

In [1]:
import numpy as np  

In [3]:
# Q1:全て0と1
print(np.ones(3))
print(np.zeros(7))

[1. 1. 1.]
[0. 0. 0. 0. 0. 0. 0.]


In [4]:
# Q2:整数のNumPy配列
o3 = np.ones(3, dtype=np.int32)
z7 = np.zeros(7, dtype=np.int32)
print(o3, o3.dtype)
print(z7, z7.dtype)

[1 1 1] int32
[0 0 0 0 0 0 0] int32


In [6]:
# Q3:中間地点に代入
xs = np.zeros(5, dtype=np.int32)
xs[2] = 1
print(xs)

[0 0 1 0 0]


In [8]:
# Q4:奇数と偶数のインデックス(1)
xs = np.zeros(10, dtype=np.int32)
xs[::2] = 1
print(xs)

[1 0 1 0 1 0 1 0 1 0]


In [9]:
# Q5:奇数と偶数のインデックス(2)
xs = np.ones(10, dtype=np.int32)
xs[::2] = 0
print(xs)

[0 1 0 1 0 1 0 1 0 1]


In [12]:
# Q6:FizzBuzz
fzbz = np.arange(1, 101, dtype=np.int32)
fzbz = fzbz.astype(np.object)
fzbz[2::3] = "Fizz"
fzbz[4::5] = "Buzz"
fzbz[14::15] = "FizzBuzz"
print(fzbz)

[1 2 'Fizz' 4 'Buzz' 'Fizz' 7 8 'Fizz' 'Buzz' 11 'Fizz' 13 14 'FizzBuzz'
 16 17 'Fizz' 19 'Buzz' 'Fizz' 22 23 'Fizz' 'Buzz' 26 'Fizz' 28 29
 'FizzBuzz' 31 32 'Fizz' 34 'Buzz' 'Fizz' 37 38 'Fizz' 'Buzz' 41 'Fizz' 43
 44 'FizzBuzz' 46 47 'Fizz' 49 'Buzz' 'Fizz' 52 53 'Fizz' 'Buzz' 56 'Fizz'
 58 59 'FizzBuzz' 61 62 'Fizz' 64 'Buzz' 'Fizz' 67 68 'Fizz' 'Buzz' 71
 'Fizz' 73 74 'FizzBuzz' 76 77 'Fizz' 79 'Buzz' 'Fizz' 82 83 'Fizz' 'Buzz'
 86 'Fizz' 88 89 'FizzBuzz' 91 92 'Fizz' 94 'Buzz' 'Fizz' 97 98 'Fizz'
 'Buzz']


In [ ]:
# Q7:FizzBuzzしばりプレイ
# Q6が既にMOD縛りをしてるので省略

In [17]:
# Q8:世界のナベアツ
ind = np.arange(1, 101, dtype=np.int32)
nbat = ind.astype(np.object)
nbat[ind%10 == 3] = "アホ"
nbat[ind//10 == 3] = "アホ"
nbat[ind%3 == 0] = "アホ"
print(nbat)

[1 2 'アホ' 4 5 'アホ' 7 8 'アホ' 10 11 'アホ' 'アホ' 14 'アホ' 16 17 'アホ' 19 20 'アホ'
 22 'アホ' 'アホ' 25 26 'アホ' 28 29 'アホ' 'アホ' 'アホ' 'アホ' 'アホ' 'アホ' 'アホ' 'アホ'
 'アホ' 'アホ' 40 41 'アホ' 'アホ' 44 'アホ' 46 47 'アホ' 49 50 'アホ' 52 'アホ' 'アホ' 55
 56 'アホ' 58 59 'アホ' 61 62 'アホ' 64 65 'アホ' 67 68 'アホ' 70 71 'アホ' 'アホ' 74
 'アホ' 76 77 'アホ' 79 80 'アホ' 82 'アホ' 'アホ' 85 86 'アホ' 88 89 'アホ' 91 92 'アホ'
 94 95 'アホ' 97 98 'アホ' 100]


In [44]:
# Q9:平方数
xs = np.arange(200, dtype=np.int32)
xs[np.logical_not(np.isclose(np.sqrt(xs)%1, 0))] = 0
print(xs)

[  0   1   0   0   4   0   0   0   0   9   0   0   0   0   0   0  16   0
   0   0   0   0   0   0   0  25   0   0   0   0   0   0   0   0   0   0
  36   0   0   0   0   0   0   0   0   0   0   0   0  49   0   0   0   0
   0   0   0   0   0   0   0   0   0   0  64   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0  81   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0 100   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0 121   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
 144   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0 169   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0 196   0
   0   0]


In [31]:
# Q10:等速直線運動
print(np.linspace(15, 65, 61))

[15.         15.83333333 16.66666667 17.5        18.33333333 19.16666667
 20.         20.83333333 21.66666667 22.5        23.33333333 24.16666667
 25.         25.83333333 26.66666667 27.5        28.33333333 29.16666667
 30.         30.83333333 31.66666667 32.5        33.33333333 34.16666667
 35.         35.83333333 36.66666667 37.5        38.33333333 39.16666667
 40.         40.83333333 41.66666667 42.5        43.33333333 44.16666667
 45.         45.83333333 46.66666667 47.5        48.33333333 49.16666667
 50.         50.83333333 51.66666667 52.5        53.33333333 54.16666667
 55.         55.83333333 56.66666667 57.5        58.33333333 59.16666667
 60.         60.83333333 61.66666667 62.5        63.33333333 64.16666667
 65.        ]


In [32]:
# Q11:連番べき乗
xs = np.arange(10) ** np.arange(10)
print(xs)

[        1         1         4        27       256      3125     46656
    823543  16777216 387420489]


In [36]:
# Q12:三角関数の加法定理
# sin(x + y) = sin(x)cos(y) + cos(x)sin(y)
alpha = np.linspace(0, 2*np.pi, 50)
beta = np.arange(50)
sahen = np.sin(alpha + beta)
uhen = np.sin(alpha)*np.cos(beta) + np.cos(alpha)*np.sin(beta)
print(np.isclose(sahen, uhen))

[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True]


In [ ]:
# Q13:GoToトラベル
